import type { Theme } from '../types';

export const DEFAULT_THEMES: Theme[] = [
  {
    id: 'default',
    name: '默认简约',
    styles: {
      global: {
        fontSize: '15px',
        lineHeight: '1.75',
        color: '#333333',
        backgroundColor: '#ffffff',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
      },
      h1: 'color: #1a1a1a; font-size: 24px; font-weight: 700; margin: 24px 0 16px; padding-bottom: 10px; border-bottom: 2px solid #e5e5e5;',
      h2: 'color: #1a1a1a; font-size: 20px; font-weight: 600; margin: 20px 0 12px;',
      h3: 'color: #1a1a1a; font-size: 18px; font-weight: 600; margin: 18px 0 10px;',
      p: 'color: #333; font-size: 15px; line-height: 1.75; margin: 0 0 16px;',
      quote: 'border-left: 4px solid #000000; padding: 12px 16px; margin: 16px 0; color: #666; background: #f9f9f9;',
      code: 'background: #f4f4f4; padding: 2px 6px; border-radius: 4px; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 14px; color: #e83e8c;',
      pre: 'background: #2d2d2d; color: #f8f8f2; padding: 16px; border-radius: 8px; overflow-x: auto; margin: 16px 0;',
      ul: 'margin: 12px 0 16px 24px; padding: 0;',
      ol: 'margin: 12px 0 16px 24px; padding: 0;',
      li: 'margin: 8px 0; line-height: 1.75;',
      a: 'color: #1890ff; text-decoration: none;',
      img: 'max-width: 100%; height: auto; border-radius: 8px; margin: 16px 0; display: block;',
      hr: 'border: none; border-top: 1px solid #e5e5e5; margin: 24px 0;',
      table: 'width: 100%; border-collapse: collapse; margin: 16px 0;',
      th: 'background: #f5f5f5; padding: 10px; border: 1px solid #e5e5e5; text-align: left; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #e5e5e5;',
    },
  },
  {
    id: 'tech-blue',
    name: '科技蓝',
    styles: {
      global: {
        fontSize: '15px',
        lineHeight: '1.8',
        color: '#2c3e50',
        backgroundColor: '#ffffff',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
      },
      h1: 'color: #1890ff; font-size: 26px; font-weight: 700; margin: 24px 0 16px; padding-bottom: 12px; border-bottom: 3px solid #1890ff;',
      h2: 'color: #096dd9; font-size: 21px; font-weight: 600; margin: 20px 0 12px; border-left: 4px solid #1890ff; padding-left: 12px;',
      h3: 'color: #1890ff; font-size: 18px; font-weight: 600; margin: 18px 0 10px;',
      p: 'color: #2c3e50; font-size: 15px; line-height: 1.8; margin: 0 0 16px;',
      quote: 'border-left: 4px solid #1890ff; padding: 14px 18px; margin: 16px 0; color: #595959; background: #e6f7ff; border-radius: 0 6px 6px 0;',
      code: 'background: #f0f5ff; padding: 3px 8px; border-radius: 4px; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 14px; color: #1890ff;',
      pre: 'background: #001529; color: #d6deeb; padding: 18px; border-radius: 8px; overflow-x: auto; margin: 16px 0;',
      ul: 'margin: 12px 0 16px 24px; padding: 0;',
      ol: 'margin: 12px 0 16px 24px; padding: 0;',
      li: 'margin: 8px 0; line-height: 1.8;',
      a: 'color: #1890ff; text-decoration: underline;',
      img: 'max-width: 100%; height: auto; border-radius: 8px; margin: 16px 0; display: block; box-shadow: 0 4px 12px rgba(24, 144, 255, 0.15);',
      hr: 'border: none; border-top: 2px solid #1890ff; margin: 24px 0;',
      table: 'width: 100%; border-collapse: collapse; margin: 16px 0;',
      th: 'background: #1890ff; color: white; padding: 12px; border: 1px solid #096dd9; text-align: left; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #d9d9d9;',
    },
  },
  {
    id: 'art-dark',
    name: '文艺黑',
    styles: {
      global: {
        fontSize: '16px',
        lineHeight: '1.9',
        color: '#1a1a1a',
        backgroundColor: '#ffffff',
        fontFamily: '"Noto Serif SC", "Source Han Serif SC", "Songti SC", Georgia, serif',
      },
      h1: 'color: #000; font-size: 28px; font-weight: 700; margin: 32px 0 20px; text-align: center; letter-spacing: 2px;',
      h2: 'color: #000; font-size: 22px; font-weight: 600; margin: 28px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #ddd;',
      h3: 'color: #333; font-size: 19px; font-weight: 600; margin: 24px 0 14px;',
      p: 'color: #2a2a2a; font-size: 16px; line-height: 1.9; margin: 0 0 20px; text-align: justify;',
      quote: 'border-left: 3px solid #000; padding: 16px 20px; margin: 24px 0; color: #444; background: #fafafa; font-style: italic;',
      code: 'background: #f0f0f0; padding: 2px 8px; border-radius: 3px; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 14px; color: #000;',
      pre: 'background: #1a1a1a; color: #e8e8e8; padding: 20px; border-radius: 4px; overflow-x: auto; margin: 20px 0;',
      ul: 'margin: 16px 0 20px 28px; padding: 0;',
      ol: 'margin: 16px 0 20px 28px; padding: 0;',
      li: 'margin: 10px 0; line-height: 1.9;',
      a: 'color: #000; text-decoration: underline;',
      img: 'max-width: 100%; height: auto; margin: 24px 0; display: block;',
      hr: 'border: none; border-top: 1px solid #000; margin: 32px 0;',
      table: 'width: 100%; border-collapse: collapse; margin: 20px 0;',
      th: 'background: #f5f5f5; padding: 12px; border: 1px solid #ddd; text-align: left; font-weight: 600;',
      td: 'padding: 10px; border: 1px solid #ddd;',
    },
  },
];
